[package]
name = "key-tools"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
rand_core = { version="0.6.3", features=["getrandom"] }
signatory = "0.22.0"
hkd32 = { version="0.6.0", features=["mnemonic"] }

[dev-dependencies]
log = "0.4"
