name: Go

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: go-cache
        uses: actions/cache@v2
        with: 
          path: module/build/gravity
          key: ${{ matrix.os }}-gravity
      - name: install-go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: go-test
        run: cd module && make test
      - name: go-build
        run: cd module && make build
  go-docker:
    permissions:
      contents: read
      packages: write
    name: go-docker
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: container-login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
